export type {
  AgentCliDescriptor,
  AgentCliId,
  AgentDefinition,
  AgentEvent,
  AgentEventType,
  AgentModelOption,
  AgentModelProbe,
  AgentModelSource,
  AgentPingResult,
  AgentProcess,
  AgentModuleId,
  AgentProfile,
  AgentProfileInput,
  AgentProfileStats,
  AgentPromptMode,
  AgentRunInput,
  AgentRunRecord,
  AgentSessionSummary,
  AgentStatus,
} from "./agent";
export type { GitDiffSummary, GitFileChange, GitFileChangeKind, ProjectSummary } from "./project";
export type {
  KnowledgeCategoryStat,
  KnowledgeCodeGraph,
  KnowledgeExportFormat,
  KnowledgeExportResult,
  KnowledgeFileInsight,
  KnowledgeGraphEdge,
  KnowledgeGraphEdgeKind,
  KnowledgeGraphNode,
  KnowledgeGraphNodeKind,
  KnowledgeLanguageStat,
  KnowledgeScanInput,
  KnowledgeSnapshot,
} from "./knowledge";
export type {
  AppIdentity,
  AppIdentityInput,
  AppIdentityStatus,
  AppLoginMethod,
  ProviderConnection,
  ProviderConnectionAuthMode,
  ProviderConnectionAuthRequest,
  ProviderConnectionAuthResult,
  ProviderConnectionInput,
  ProviderConnectionProvider,
  ProviderConnectionStatus,
  ProviderConnectionStorageMode,
} from "./settings";
export type { CliDiagnostic, SystemDiagnostics } from "./system";
export type {
  TaskDifficulty,
  TaskEvent,
  TaskEventType,
  TaskPlanInput,
  TaskPlanResult,
  TaskPlanSummary,
  TaskRecord,
  TaskSaveInput,
  TaskScheduleTickResult,
  TaskStatus,
} from "./task";
export type {
  WorkflowActivityEntry,
  WorkflowActivityKind,
  WorkflowDefinition,
  WorkflowEvent,
  WorkflowEventType,
  WorkflowExportResult,
  WorkflowMetrics,
  WorkflowRunOptions,
  WorkflowRunRecord,
  WorkflowRunStatus,
  WorkflowSaveInput,
  WorkflowStats,
  WorkflowStatus,
  WorkflowStepDefinition,
  WorkflowStepKind,
  WorkflowStepRunRecord,
  WorkflowTrigger,
  WorkflowTriggerType,
} from "./workflow";
export type { AgenticDesktopApi } from "./ipc";
