export type {
  AgentCliDescriptor,
  AgentCliId,
  AgentCliOption,
  AgentDefinition,
  AgentEvent,
  AgentEventType,
  AgentModelOption,
  AgentModelProbe,
  AgentModelSource,
  AgentOptionChoice,
  AgentOptionKind,
  AgentOptionValue,
  AgentOptionValues,
  AgentPingResult,
  AgentProcess,
  AgentModuleId,
  AgentProfile,
  AgentProfileInput,
  AgentProfileStats,
  AgentPromptMode,
  AgentRunInput,
  AgentRunRecord,
  AgentSessionSummary,
  AgentStatus,
  AgentStructuredChat,
} from "./agent";
export type {
  GitCommitSummary,
  GitDiffSummary,
  GitFileChange,
  GitFileChangeKind,
  GitFileDiff,
  GitOperationResult,
  ProjectSummary,
} from "./project";
export type {
  KnowledgeCategoryStat,
  KnowledgeCodeGraph,
  KnowledgeExportFormat,
  KnowledgeExportResult,
  KnowledgeFileInsight,
  KnowledgeGraphEdge,
  KnowledgeGraphEdgeKind,
  KnowledgeGraphNode,
  KnowledgeGraphNodeKind,
  KnowledgeLanguageStat,
  KnowledgeScanInput,
  KnowledgeSnapshot,
  KnowledgeTruncationReport,
} from "./knowledge";
export type {
  AppIdentity,
  AppIdentityInput,
  AppIdentityStatus,
  AppLoginMethod,
  ProviderConnection,
  ProviderConnectionAuthMode,
  ProviderConnectionAuthRequest,
  ProviderConnectionAuthResult,
  ProviderConnectionInput,
  ProviderConnectionProvider,
  ProviderConnectionStatus,
  ProviderConnectionStorageMode,
  ProviderConnectionVerifyResult,
  ProviderVerificationOutcome,
} from "./settings";
export type {
  CliDiagnostic,
  DiagnosticAction,
  DiagnosticCheck,
  DiagnosticStatus,
  SystemDiagnostics,
} from "./system";
export type {
  TaskDifficulty,
  TaskEvent,
  TaskEventType,
  TaskPlanInput,
  TaskPlanResult,
  TaskPlanSummary,
  TaskRecord,
  TaskSaveInput,
  TaskScheduleTickResult,
  TaskStatus,
} from "./task";
export type {
  WorkflowActivityEntry,
  WorkflowActivityKind,
  WorkflowDefinition,
  WorkflowEvent,
  WorkflowEventType,
  WorkflowExportResult,
  WorkflowMetrics,
  WorkflowRunOptions,
  WorkflowRunRecord,
  WorkflowRunStatus,
  WorkflowSaveInput,
  WorkflowStats,
  WorkflowStatus,
  WorkflowStepDefinition,
  WorkflowStepKind,
  WorkflowStepOutcome,
  WorkflowStepRunRecord,
  WorkflowTrigger,
  WorkflowTriggerType,
} from "./workflow";
export type { AgenticDesktopApi } from "./ipc";
export { buildOptionArgs } from "./agent-options";
export type { AgentOptionArgContext } from "./agent-options";
