import type { WorkflowDefinition, WorkflowStepDefinition } from "@contracts";

type SeedStep = Omit<WorkflowStepDefinition, "id" | "order"> & { id: string };

export type WorkflowSeed = Omit<WorkflowDefinition, "createdAt" | "updatedAt" | "steps" | "stats"> & {
  createdAt: string;
  updatedAt: string;
  steps: SeedStep[];
};

function step(partial: Partial<SeedStep> & Pick<SeedStep, "id" | "name" | "kind" | "instruction">): SeedStep {
  return {
    summary: partial.summary ?? "",
    cliId: partial.cliId ?? "claude",
    model: partial.model ?? "claude-sonnet-4.5",
    shellCommand: partial.shellCommand,
    timeoutSeconds: partial.timeoutSeconds ?? 600,
    requiresApproval: partial.requiresApproval ?? false,
    continueOnError: partial.continueOnError ?? false,
    enabled: partial.enabled ?? true,
    ...partial,
  };
}

const now = "2025-05-30T09:00:00.000Z";

export const workflowSeeds: WorkflowSeed[] = [
  {
    id: "wf-content-creation",
    name: "Content Creation Flow",
    description: "End-to-end content creation and publishing workflow",
    status: "active",
    favorite: true,
    owner: "Sarah Chen",
    projectPath: null,
    trigger: { type: "schedule", schedule: "Daily, 9:00 AM", detail: "Local scheduler" },
    integrations: ["ContentGPT Agent", "Web Search", "Notion", "Slack", "Email"],
    createdAt: "2025-04-12T09:00:00.000Z",
    updatedAt: now,
    steps: [
      step({
        id: "step-content-trigger",
        name: "Trigger",
        kind: "trigger",
        summary: "Scheduled • Daily, 9:00 AM",
        cliId: "shell",
        model: "local",
        instruction: "Collect the content brief queue and expose it to the next steps.",
        shellCommand: "echo \"content brief queue ready\"",
        timeoutSeconds: 60,
      }),
      step({
        id: "step-content-analyze",
        name: "Analyze",
        kind: "analyze",
        summary: "Content analysis and research",
        cliId: "claude",
        model: "claude-sonnet-4.5",
        instruction:
          "Investigate the topic queue. Research audience intent, competitor coverage, and gaps. Return an outline with headings, key claims, and sources.",
        timeoutSeconds: 900,
      }),
      step({
        id: "step-content-review",
        name: "Review",
        kind: "review",
        summary: "Human review and approval",
        cliId: "kiro",
        model: "kiro-review",
        instruction:
          "Review the generated outline for factual accuracy, tone, and brand guidelines. Flag anything that needs a human decision.",
        requiresApproval: true,
        timeoutSeconds: 600,
      }),
      step({
        id: "step-content-execute",
        name: "Execute",
        kind: "execute",
        summary: "Generate and publish content",
        cliId: "claude",
        model: "claude-sonnet-4.5",
        instruction:
          "Write the final article from the approved outline, then prepare the publish payload (title, slug, body, tags).",
        timeoutSeconds: 1200,
      }),
      step({
        id: "step-content-notify",
        name: "Notify",
        kind: "notify",
        summary: "Notify stakeholders",
        cliId: "shell",
        model: "local",
        instruction: "Send the publish summary to the content channel.",
        shellCommand: "echo \"published content summary sent\"",
        timeoutSeconds: 120,
        continueOnError: true,
      }),
    ],
  },
  {
    id: "wf-code-review",
    name: "Code Review Pipeline",
    description: "Automated code review and quality checks",
    status: "active",
    favorite: false,
    owner: "Marcus Reed",
    projectPath: null,
    trigger: { type: "manual", detail: "Run manually after a push (no local push runner yet)" },
    integrations: ["Kiro CLI", "Claude CLI", "GitHub", "Slack"],
    createdAt: "2025-03-02T09:00:00.000Z",
    updatedAt: "2025-05-30T08:55:00.000Z",
    steps: [
      step({
        id: "step-review-trigger",
        name: "Trigger",
        kind: "trigger",
        summary: "On push • GitHub",
        cliId: "shell",
        model: "local",
        instruction: "Capture the incoming commit range for review.",
        shellCommand: "git log -1 --stat",
        timeoutSeconds: 60,
      }),
      step({
        id: "step-review-investigate",
        name: "Investigate",
        kind: "investigate",
        summary: "Map the changed surface area",
        cliId: "kiro",
        model: "kiro-default",
        instruction:
          "Investigate the diff: list changed files, affected modules, risky call sites, and any missing tests. Do not modify files.",
        timeoutSeconds: 600,
      }),
      step({
        id: "step-review-review",
        name: "Review",
        kind: "review",
        summary: "Quality and correctness review",
        cliId: "claude",
        model: "claude-sonnet-4.5",
        instruction:
          "Review the diff for correctness, readability, and project conventions. Produce inline-style comments grouped by file.",
        timeoutSeconds: 900,
      }),
      step({
        id: "step-review-security",
        name: "Security scan",
        kind: "test",
        summary: "Static and dependency checks",
        cliId: "shell",
        model: "local",
        instruction: "Run static analysis and dependency audit for the changed packages.",
        shellCommand: "npm run typecheck",
        timeoutSeconds: 900,
        continueOnError: true,
      }),
      step({
        id: "step-review-notify",
        name: "Notify",
        kind: "notify",
        summary: "Post review summary",
        cliId: "shell",
        model: "local",
        instruction: "Publish the aggregated review summary back to the pull request.",
        shellCommand: "echo \"review summary posted\"",
        timeoutSeconds: 120,
        continueOnError: true,
      }),
    ],
  },
  {
    id: "wf-bug-triage",
    name: "Bug Triage Flow",
    description: "Intake, prioritize, and route bugs automatically",
    status: "active",
    favorite: false,
    owner: "Priya Nair",
    projectPath: null,
    trigger: { type: "manual", detail: "Run manually per issue (no tracker integration yet)" },
    integrations: ["Kiro CLI", "Gemini CLI", "Jira", "Slack"],
    createdAt: "2025-02-18T09:00:00.000Z",
    updatedAt: "2025-05-30T08:48:00.000Z",
    steps: [
      step({
        id: "step-bug-trigger",
        name: "Trigger",
        kind: "trigger",
        summary: "On create • Jira",
        cliId: "shell",
        model: "local",
        instruction: "Pull the new issue payload into the run context.",
        shellCommand: "echo \"issue payload received\"",
        timeoutSeconds: 60,
      }),
      step({
        id: "step-bug-investigate",
        name: "Investigate",
        kind: "investigate",
        summary: "Reproduce and locate root cause",
        cliId: "kiro",
        model: "kiro-default",
        instruction:
          "Investigate the bug report: search the codebase for the failing path, try to reproduce from the description, and identify the most likely root cause with file and line references.",
        timeoutSeconds: 1200,
      }),
      step({
        id: "step-bug-classify",
        name: "Classify",
        kind: "analyze",
        summary: "Severity, priority, and owner",
        cliId: "gemini",
        model: "gemini-2.5-pro",
        instruction:
          "Classify severity (S1-S4) and priority from the investigation notes, then propose the owning team and labels.",
        timeoutSeconds: 300,
      }),
      step({
        id: "step-bug-route",
        name: "Route",
        kind: "execute",
        summary: "Assign and link duplicates",
        cliId: "shell",
        model: "local",
        instruction: "Apply labels, assign the owner, and link duplicate issues.",
        shellCommand: "echo \"issue routed\"",
        timeoutSeconds: 180,
      }),
      step({
        id: "step-bug-notify",
        name: "Notify",
        kind: "notify",
        summary: "Notify the owning team",
        cliId: "shell",
        model: "local",
        instruction: "Send the triage decision to the owning team channel.",
        shellCommand: "echo \"triage notification sent\"",
        timeoutSeconds: 120,
        continueOnError: true,
      }),
    ],
  },
  {
    id: "wf-deployment-approval",
    name: "Deployment Approval Flow",
    description: "Multi-step deployment approval and notifications",
    status: "active",
    favorite: false,
    owner: "Alex Morgan",
    projectPath: null,
    trigger: { type: "manual", detail: "Manually triggered" },
    integrations: ["Codex CLI", "GitHub", "Docker", "Email"],
    createdAt: "2025-01-24T09:00:00.000Z",
    updatedAt: "2025-05-30T08:10:00.000Z",
    steps: [
      step({
        id: "step-deploy-trigger",
        name: "Trigger",
        kind: "trigger",
        summary: "Manual • release captain",
        cliId: "shell",
        model: "local",
        instruction: "Capture the release tag and target environment.",
        shellCommand: "git describe --tags --always",
        timeoutSeconds: 60,
      }),
      step({
        id: "step-deploy-investigate",
        name: "Pre-flight investigation",
        kind: "investigate",
        summary: "Diff, migrations, and risk",
        cliId: "codex",
        model: "gpt-5-codex",
        instruction:
          "Investigate the release diff for schema migrations, config changes, and rollback risk. Produce a go/no-go checklist.",
        timeoutSeconds: 900,
      }),
      step({
        id: "step-deploy-approval",
        name: "Approval",
        kind: "approval",
        summary: "Human sign-off required",
        cliId: "shell",
        model: "local",
        instruction: "Block until a human approves the go/no-go checklist.",
        shellCommand: "echo \"awaiting approval\"",
        requiresApproval: true,
        timeoutSeconds: 86400,
      }),
      step({
        id: "step-deploy-execute",
        name: "Deploy",
        kind: "deploy",
        summary: "Roll out to the target environment",
        cliId: "shell",
        model: "local",
        instruction: "Run the deployment pipeline for the approved release tag.",
        shellCommand: "echo \"deployment started\"",
        timeoutSeconds: 3600,
      }),
      step({
        id: "step-deploy-notify",
        name: "Notify",
        kind: "notify",
        summary: "Announce the rollout",
        cliId: "shell",
        model: "local",
        instruction: "Announce the rollout result with version and duration.",
        shellCommand: "echo \"deployment notification sent\"",
        timeoutSeconds: 120,
        continueOnError: true,
      }),
    ],
  },
  {
    id: "wf-research-analysis",
    name: "Research Analysis Flow",
    description: "Research, analyze, and synthesize insights",
    status: "paused",
    favorite: false,
    owner: "Sarah Chen",
    projectPath: null,
    trigger: { type: "schedule", schedule: "Weekly, Mon 10:00 AM", detail: "Local scheduler" },
    integrations: ["Gemini CLI", "Web Search", "Notion"],
    createdAt: "2025-03-15T09:00:00.000Z",
    updatedAt: "2025-05-30T06:10:00.000Z",
    steps: [
      step({
        id: "step-research-trigger",
        name: "Trigger",
        kind: "trigger",
        summary: "Scheduled • Weekly, Mon 10:00 AM",
        cliId: "shell",
        model: "local",
        instruction: "Load the research question backlog.",
        shellCommand: "echo \"research backlog loaded\"",
        timeoutSeconds: 60,
      }),
      step({
        id: "step-research-investigate",
        name: "Investigate",
        kind: "investigate",
        summary: "Primary source gathering",
        cliId: "gemini",
        model: "gemini-2.5-pro",
        instruction:
          "Investigate each research question. Gather primary sources, note publication dates, and record contradicting evidence.",
        timeoutSeconds: 1800,
      }),
      step({
        id: "step-research-analyze",
        name: "Synthesize",
        kind: "analyze",
        summary: "Cluster findings into insights",
        cliId: "claude",
        model: "claude-sonnet-4.5",
        instruction:
          "Synthesize the gathered sources into ranked insights with confidence levels and open questions.",
        timeoutSeconds: 900,
      }),
      step({
        id: "step-research-review",
        name: "Review",
        kind: "review",
        summary: "Fact-check the synthesis",
        cliId: "kiro",
        model: "kiro-default",
        instruction: "Fact-check each insight against the cited source and remove unsupported claims.",
        timeoutSeconds: 600,
      }),
      step({
        id: "step-research-notify",
        name: "Publish",
        kind: "notify",
        summary: "Ship the research digest",
        cliId: "shell",
        model: "local",
        instruction: "Publish the digest to the research workspace.",
        shellCommand: "echo \"research digest published\"",
        timeoutSeconds: 120,
        continueOnError: true,
      }),
    ],
  },
];
